
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
pub struct EditUsuarioDto {
    pub id: String, // ID of the usuario to update
    pub nome: Option<String>,
    pub ativo: Option<i32>,
    pub cpf: Option<String>,
    pub rg: Option<String>,
    pub data_nasc: Option<String>,
    pub telefone: Option<String>,
    pub profissao: Option<String>,
    pub escolaridade: Option<i32>,
    pub patologia: Option<String>,
    pub cep: Option<String>,
    pub municipio: Option<String>,
    pub bairro: Option<String>,
    pub rua: Option<String>,
    pub numero: Option<String>,
    pub referencia: Option<String>,
    pub resp_nome: Option<String>,
    pub resp_cpf: Option<String>,
    pub resp_idade: Option<i32>,
    pub resp_telefone: Option<String>,
    pub resp_profissao: Option<String>,
    pub resp_escolaridade: Option<i32>,
    pub resp_parentesco: Option<String>,
    pub resp_renda: Option<String>,
    pub fonte_renda: Option<String>,
    pub valor_renda: Option<f64>,
    pub moradia: Option<String>,
    pub moradia_valor: Option<f64>,
    pub agua: Option<String>,
    pub agua_valor: Option<f64>,
    pub energia: Option<String>,
    pub energia_valor: Option<f64>,
    pub bens: Option<String>,
    pub internet: Option<bool>,
    pub cras: Option<bool>,
    pub acesso_cras: Option<String>,
    pub desc_doenca: Option<String>,
    pub medicamentos: Option<String>,
    pub medicamentos_gasto: Option<f64>,
    pub tratamento: Option<String>,
    pub nutri: Option<String>,
    pub tempo_tratamento: Option<String>,
    pub local: Option<String>,
    pub encaminhamento: Option<String>,
    pub solicitacoes: Option<String>,
    pub observacoes: Option<String>,
    pub motivo_desligamento: Option<String>,
    pub parecer_social: Option<String>,
    pub operador_id: Option<i64>,
}